package com.bank.bian.systemsadministration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Systems Administration
 *
 * Business Area:      Business Support
 * Business Domain:    Technology and Operations
 * Functional Pattern: Administer
 * Asset Type:         System Configuration
 * Control Record:     System Configuration Administrative Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Systems Administration — BIAN Semantic API")
                .description("Service Domain 'Systems Administration' (Administer pattern) "
                        + "operating on the 'System Configuration Administrative Plan' control record.")
                .version("0.1.0"));
    }
}
